import Head from "next/head";
import Image from "next/image";
import { Hero, HeroInfo } from "../styles/HeroStyles";
import Product from "../components/Product";
import { Gallery } from "../styles/Gallery";
import { useUser } from "@auth0/nextjs-auth0";
import { useEffect } from "react";

export default function Home({ data }) {
  const { user } = useUser();
  const sendUser = async () => {
    try {
      await fetch(`/api/user`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(user),
      });
    } catch (error) {
      console.error(error);
    }
  };
  useEffect(() => {
    if (user) {
      sendUser();
    }
  }, []);
  // Filter data
  const { jordans, nike, adidas, puma } = data;
  return (
    <div>
      <Head>
        <title>Jumpman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <div>
          <img src="/images/summer jays.jpg" alt="Jordan 1" />
        </div>
        <HeroInfo>
          <h1>JORDAN 4S AND JORDAN 1S</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            consectetur explicabo repellendus neque vel consequatur fugiat.
            Itaque, sequi assumenda laboriosam, atque omnis, cum modi alias fuga
            esse nemo animi incidunt perferendis natus. Rem quaerat, tenetur
            ipsam officia quas voluptas nobis voluptatibus, doloremque eum
            minima velit deleniti odit? Fugit, deserunt nisi.
          </p>
        </HeroInfo>
      </Hero>
      <Gallery>
        {jordans.map((product) => (
          <Product key={product.product_slug} product={product} />
        ))}
      </Gallery>
      <Hero>
        <HeroInfo>
          <h1>NIKEY SHOES</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            consectetur explicabo repellendus neque vel consequatur fugiat.
            Itaque, sequi assumenda laboriosam, atque omnis, cum modi alias fuga
            esse nemo animi incidunt perferendis natus. Rem quaerat, tenetur
            ipsam officia quas voluptas nobis voluptatibus, doloremque eum
            minima velit deleniti odit? Fugit, deserunt nisi.
          </p>
        </HeroInfo>
        <div>
          <img src="/images/jordan 1 retro.png" alt="Jordans" />
        </div>
      </Hero>
      <Gallery>
        {nike.map((product) => (
          <Product key={product.product_slug} product={product} />
        ))}
      </Gallery>
      <Hero>
        <div>
          <img src="/images/adidas boots.webp" alt="Adidas" />
        </div>
        <HeroInfo>
          <h1>THREE STRIPES LIFESTYLE</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            consectetur explicabo repellendus neque vel consequatur fugiat.
            Itaque, sequi assumenda laboriosam, atque omnis, cum modi alias fuga
            esse nemo animi incidunt perferendis natus. Rem quaerat, tenetur
            ipsam officia quas voluptas nobis voluptatibus, doloremque eum
            minima velit deleniti odit? Fugit, deserunt nisi.
          </p>
        </HeroInfo>
      </Hero>
      <Gallery>
        {adidas.map((product) => (
          <Product key={product.product_slug} product={product} />
        ))}
      </Gallery>
      <Hero>
        <HeroInfo>
          <h1>SO YOU WANNA GO TO THE MOON?</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            consectetur explicabo repellendus neque vel consequatur fugiat.
            Itaque, sequi assumenda laboriosam, atque omnis, cum modi alias fuga
            esse nemo animi incidunt perferendis natus. Rem quaerat, tenetur
            ipsam officia quas voluptas nobis voluptatibus, doloremque eum
            minima velit deleniti odit? Fugit, deserunt nisi.
          </p>
        </HeroInfo>
        <div>
          <img src="/images/yeezy-knit-runner.jpg" alt="yeezy knit runner" />
        </div>
      </Hero>
      <Gallery>
        {puma.map((product) => (
          <Product key={product.product_slug} product={product} />
        ))}
      </Gallery>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/products");
  const data = await res.json();
  return {
    props: { data },
  };
}
