import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jumpman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <div>
          <img src="/images/summer jays.jpg" alt="Jordan 1" />
        </div>
        <HeroInfo>
          <h1>JORDAN 4S AND JORDAN 1S</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            consectetur explicabo repellendus neque vel consequatur fugiat.
            Itaque, sequi assumenda laboriosam, atque omnis, cum modi alias fuga
            esse nemo animi incidunt perferendis natus. Rem quaerat, tenetur
            ipsam officia quas voluptas nobis voluptatibus, doloremque eum
            minima velit deleniti odit? Fugit, deserunt nisi.
          </p>
        </HeroInfo>
      </Hero>
      <Hero>
        <HeroInfo>
          <h1>NIKEY SHOES</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            consectetur explicabo repellendus neque vel consequatur fugiat.
            Itaque, sequi assumenda laboriosam, atque omnis, cum modi alias fuga
            esse nemo animi incidunt perferendis natus. Rem quaerat, tenetur
            ipsam officia quas voluptas nobis voluptatibus, doloremque eum
            minima velit deleniti odit? Fugit, deserunt nisi.
          </p>
        </HeroInfo>
        <div>
          <img src="/images/jordan 1 retro.png" alt="Jordans" />
        </div>
      </Hero>
      <Hero>
        <div>
          <img src="/images/adidas boots.webp" alt="Adidas" />
        </div>
        <HeroInfo>
          <h1>THREE STRIPES LIFESTYLE</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            consectetur explicabo repellendus neque vel consequatur fugiat.
            Itaque, sequi assumenda laboriosam, atque omnis, cum modi alias fuga
            esse nemo animi incidunt perferendis natus. Rem quaerat, tenetur
            ipsam officia quas voluptas nobis voluptatibus, doloremque eum
            minima velit deleniti odit? Fugit, deserunt nisi.
          </p>
        </HeroInfo>
      </Hero>
      <Hero>
        <HeroInfo>
        <h1>SO YOU WANNA GO TO THE MOON?</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            consectetur explicabo repellendus neque vel consequatur fugiat.
            Itaque, sequi assumenda laboriosam, atque omnis, cum modi alias fuga
            esse nemo animi incidunt perferendis natus. Rem quaerat, tenetur
            ipsam officia quas voluptas nobis voluptatibus, doloremque eum
            minima velit deleniti odit? Fugit, deserunt nisi.
          </p>
        </HeroInfo>
        <div>
        <img src="/images/yeezy-knit-runner.jpg" alt="yeezy knit runner" />
        </div>
      </Hero>
    </div>
  );
}

const Hero = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 2rem;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 3rem;
  div {
    img {
      max-width: 100%;
    }
  }
`;

const HeroInfo = styled.div`
  h1,
  p {
    font-size: 1.5rem;
  }
`;
